# 3 Replicas, stores config in PV, mapping 30001 node port to provide service.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nagios-core
  template:
    metadata:
      labels:
        app: nagios-core
    spec:
      containers:
        - name: nagios-container
          image: fuhuixiao/gsd:latest
          volumeMounts:
          - name: nagios-persistent-storage
            mountPath: "/usr/local/nagios/etc/objects/"
      volumes:
        - name: nagios-persistent-storage
          persistentVolumeClaim:
            claimName: pv-claim-nagios
      nodeSelector:
        kubernetes.io/os: "linux"
---
apiVersion: v1
kind: Service
metadata:
  name: nagios-service
spec:
  type: NodePort
  selector:
    app: nagios-core
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
---
# PVC, 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-nagios
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
# PV, 1Gi
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-nagios
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <Your Server Name>
    path: "<Your NFS Server Path>"

